version: "3.9"

services:
  postgres:
    image: postgres:${POSTGRES_RELEASE}
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    deploy:
      restart_policy:
        max_attempts: 10
        window: 120s
  main:
    #image: 
    env_file: .env
    command: "python3"
    ports:
      - "8000:8000"
    deploy:
      replicas: 1 
      restart_policy:
        max_attempts: 10
        window: 120s
    depends_on:
      - postgres
