version: "3.9"

services:
  postgres:
    image: postgres:17
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    deploy:
      update_config:
        order: start-first
      restart_policy:
        max_attempts: 10
        window: 120s
  main:
    image: 
    env_file: .env
    command: ""
    ports:
      - "8000:8000"
    deploy:
      replicas: 1 
      restart_policy:
        max_attempts: 10
        window: 120s
    depends_on:
      - postgres
