# Generated by Django 4.2.16 on 2024-11-04 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameMetaData',
            fields=[
                ('package_name', models.TextField(primary_key=True, serialize=False)),
                ('game_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField()),
                ('ended', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.TextField()),
                ('platform', models.TextField(choices=[('iOS', 'Ios'), ('Android', 'Android'), ('Other', 'Other')])),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.game')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField()),
                ('status', models.TextField(choices=[('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Pending', 'Pending'), ('NotStarted', 'Notstarted'), ('Preempted', 'Preemped')])),
                ('num_failures', models.IntegerField(default=0)),
                ('statistics', models.JSONField(default=dict)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.session')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.user')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='package_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.gamemetadata'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_blob', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.session')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.task')),
            ],
        ),
    ]
